### ISSUE TITLE
Target: spec.address contains port, which should be removed

### ISSUE THREAD

**Issue by steiler** [sdcio/config-server#36]
The Target CR as created by the discovery controller populates the address field with not just the address but also the port.

The port however should be taken on demand from the Connection or the Sync-Profile.
```yaml
apiVersion: inv.sdcio.dev/v1alpha1
kind: Target
metadata:
  ...
spec:
  address: 172.18.0.5:57400
  connectionProfile: gnmi-skipverify
  credentials: srl.nokia.sdcio.dev
  provider: srl.nokia.sdcio.dev
  syncProfile: gnmi-onchange
```
